### ISSUE TITLE
Write a .app wrapper for the shell script

### ISSUE THREAD

**Issue by onionhoney** [onionhoney/cs32-hw2-test#3]
To enhance user experience, we can write a .app wrapper for the shell script. It would bother some potential users to `cd` into current directory and then do `chmod`.

**Comment by colinxy** [comment]
Completely unnecessary

**Comment by onionhoney** [comment]
**Update**: 
However much unnecessary, I decided to do it for the people! The Applescript took me quite a while, as I couldn't get the relative path set right. I finally realized that the Applescript doesn't `cd` for you. A `cd` command before executing the shell script fixed the issue. 

I also tried to run iTerm if it exists, but it looks like iTerm doesn't provide API similar to those of Terminal for Applescript. I will leave this out for the future.
